/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBackground: typeof import('./src/components/AppBackground.vue')['default']
    AppEditor: typeof import('./src/components/AppEditor.vue')['default']
    FileUpload: typeof import('./src/components/FileUpload.vue')['default']
  }
}
